---
title: "Penn insurance births cleanup"
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 3
    toc_float: true
    df_print: paged
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })
---

WHYY project data cleanup. Problem was inconsistent data in multiple sheets that needed to be combined into single data frame.

```{r setup, echo=T, results='hide', message=F, warning=F}
library(tidyverse)
library(readxl)
library(purrr)
library(janitor)
```

## Import

This comes from [read-xl workflows](https://readxl.tidyverse.org/articles/articles/readxl-workflows.html#concatenate-worksheets-into-one-data-frame-1).

```{r}
path <- "data-raw/insurance-births-year-hospital-philadelphia-correct-names-edit.xlsx"
sheets <- excel_sheets(path)
births <-
  lapply(excel_sheets(path), read_excel, path = path)
births <- lapply(seq_along(sheets), function(i) {
  data.frame(sheet = I(sheets[i]), births[[i]])
})
births <- do.call(rbind, births)

births <- births %>% clean_names()

births %>% glimpse()
```

## Cleaning

```{r}
births <- births %>% 
  mutate(
    hospital = hospital %>% str_to_upper(),
    private = private %>% as.numeric(),
    medicaid = private %>% as.numeric(),
    self_pay_uninsured = private %>% as.numeric(),
    other = private %>% as.numeric(),
    unknown = private %>% as.numeric(),
  )
  
```
## Export

```{r}
births %>% write_excel_csv("data-processed/phi-ins-births.csv")

```
